flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- commonmark-0.2.1
- skylighting-core-0.10.5.2
- skylighting-0.10.5.2
- git: https://github.com/argent0/pandoc-types
  commit: 701f101e4608663074b67c83b2c687433e1f7ae4
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.0
nix:
  packages: [zlib]
